source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'unlockVitta' do

    pod 'AFNetworking'     
  
    pod 'MBProgressHUD'
    pod 'MJRefresh' 
    
    pod 'UMCCommon'
    pod 'UMCAnalytics'
    pod 'UMCSecurityPlugins'

    pod 'AMap3DMap'
    pod 'JPush'
    
end
